mkdir logs
mkdir logs/celery
mkdir logs/cron
mkdir logs/errors 
mkdir logs/gunicorn 
mkdir logs/kafka
mkdir logs/geowatch
mkdir logs/memcached
mkdir logs/requests 
mkdir logs/supervisord
mkdir logs/zookeeper
